YazarWebUygulamasi/MVCProjeKampi/MVCProjeKampi/Controllers/SkillController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCProjeKampi.Controllers
{
    public class SkillController : Controller
    {
        SkillManager sm = new SkillManager(new EfSkillDal());
        public ActionResult Index()
        {
            var meSkill = sm.GetByID(1);
            return View(meSkill);
        }
        [HttpGet]
        public ActionResult EditSkill()
        {
            var skillValue = sm.GetByID(1);
            return View(skillValue);
        }
        [HttpPost]
        public ActionResult EditSkill(Skill skill)
        {
            sm.UpdateSkill(skill);
            return RedirectToAction("Index");
        }
    }
}

YazarWebUygulamasi/MVCProjeKampi/MVCProjeKampi/Views/Skill/EditSkill.cshtml
@model EntityLayer.Concrete.Skill
@{
    ViewBag.Title = "EditSkill";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2>Yetenek Kartı Güncelleme Sayfası</h2>
@using (Html.BeginForm("EditSkill", "Skill", FormMethod.Post))
{
<div class="form-group">
    @Html.HiddenFor(x => x.ID)
    @Html.Label("Ad")
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    @Html.Label("Soyad")
    @Html.TextBoxFor(x => x.Surname, new { @class = "form-control" })
    @Html.Label("Görevi")
    @Html.TextBoxFor(x => x.TitleInfo, new { @class = "form-control" })
    @Html.Label("Yetenek 1")
    @Html.TextBoxFor(x => x.Ability1, new { @class = "form-control" })
    @Html.Label("Yetenek 1 Puanı")
    @Html.TextBoxFor(x => x.AbilityRate1, new { @class = "form-control" })
    @Html.Label("Yetenek 2")
    @Html.TextBoxFor(x => x.Ability2, new { @class = "form-control" })
    @Html.Label("Yetenek 2 Puanı")
    @Html.TextBoxFor(x => x.AbilityRate2, new { @class = "form-control" })
    @Html.Label("Yetenek 3")
    @Html.TextBoxFor(x => x.Ability3, new { @class = "form-control" })
    @Html.Label("Yetenek 3 Puanı")
    @Html.TextBoxFor(x => x.AbilityRate3, new { @class = "form-control" })
    @Html.Label("Yetenek 4")
    @Html.TextBoxFor(x => x.Ability4, new { @class = "form-control" })
    @Html.Label("Yetenek 4 Puanı")
    @Html.TextBoxFor(x => x.AbilityRate4, new { @class = "form-control" })
    @Html.Label("Yetenek 5")
    @Html.TextBoxFor(x => x.Ability5, new { @class = "form-control" })
    @Html.Label("Yetenek 5 Puanı")
    @Html.TextBoxFor(x => x.AbilityRate4, new { @class = "form-control" })
    @Html.Label("Yetenek 6")
    @Html.TextBoxFor(x => x.Ability6, new { @class = "form-control" })
    @Html.Label("Yetenek 6 Puanı")
    @Html.TextBoxFor(x => x.AbilityRate6, new { @class = "form-control" })
    @Html.Label("Yetenek 7")
    @Html.TextBoxFor(x => x.Ability7, new { @class = "form-control" })
    @Html.Label("Yetenek 7 Puanı")
    @Html.TextBoxFor(x => x.AbilityRate7, new { @class = "form-control" })
    @Html.Label("Yetenek 8")
    @Html.TextBoxFor(x => x.Ability8, new { @class = "form-control" })
    @Html.Label("Yetenek 8 Puanı")
    @Html.TextBoxFor(x => x.AbilityRate8, new { @class = "form-control" })
    @Html.Label("Facebook Url")
    @Html.TextBoxFor(x => x.FacebookUrl, new { @class = "form-control" })
    @Html.Label("Linkedin Url")
    @Html.TextBoxFor(x => x.LinkedinUrl, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Güncelle</button>
</div>}

YazarWebUygulamasi/MVCProjeKampi/MVCProjeKampi/Views/Skill/Index.cshtml
@model EntityLayer.Concrete.Skill
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Yetenek Kartım</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Skills Profile Widget template Responsive, Login form web template,Flat Pricing tables,Flat Drop downs  Sign up Web Templates, Flat Web Templates, Login sign up Responsive web template, SmartPhone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
   
    <link href="~/AdminLTE-3.0.4/Skills_Theme/web/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <link href='//fonts.googleapis.com/css?family=Questrial' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <script src="~/AdminLTE-3.0.4/Skills_Theme/web/js/jquery-1.11.1.min.js"></script>
    <script src="~/AdminLTE-3.0.4/Skills_Theme/web/js/easyResponsiveTabs.js" type="text/javascript"></script>
    <script type="text/javascript">
	$(document).ready(function () {
		$('#horizontalTab').easyResponsiveTabs({
			type: 'default',
			width: 'auto', 
			fit: true   
		});
	});
    </script>
</head>
<body>
    <div class="main">
        <h1>Yetenek Kartım</h1>
        <div class="main-info w3l">
            <div class="main-row">
                <div class="profile-grid logo wthree">
                    <img style="height:200px;width:200px" src="@Html.DisplayFor(x=>x.ImageUrl)" />
                    <h2>@Html.DisplayFor(x => x.Name) @Html.DisplayFor(x => x.Surname)</h2>
                    <p>@Html.DisplayFor(x => x.TitleInfo)</p>

                </div>
                <h3 class="title">Yetenekler</h3>
                <div class="col-md-6 skills-right bar_group">

                    <div class='bar_group__bar thin' label='@Html.DisplayFor(x=>x.Ability1)&nbsp;&nbsp; @Html.DisplayFor(x=>x.AbilityRate1)' value='180'></div>
                    <div class='bar_group__bar thin' label='@Html.DisplayFor(x=>x.Ability2)&nbsp;&nbsp; @Html.DisplayFor(x=>x.AbilityRate2)' value='175'></div>
                    <div class='bar_group__bar thin' label='@Html.DisplayFor(x=>x.Ability3)&nbsp;&nbsp; @Html.DisplayFor(x=>x.AbilityRate3)' value='160'></div>
                    <div class='bar_group__bar thin' label='@Html.DisplayFor(x=>x.Ability4)&nbsp;&nbsp; @Html.DisplayFor(x=>x.AbilityRate4)' value='100'></div>
                    <div class='bar_group__bar thin' label='@Html.DisplayFor(x=>x.Ability5)&nbsp;&nbsp; @Html.DisplayFor(x=>x.AbilityRate5)' value='190'></div>
                    <div class='bar_group__bar thin' label='@Html.DisplayFor(x=>x.Ability6)&nbsp;&nbsp; @Html.DisplayFor(x=>x.AbilityRate6)' value='185'></div>
                    <div class='bar_group__bar thin' label='@Html.DisplayFor(x=>x.Ability7)&nbsp;&nbsp; @Html.DisplayFor(x=>x.AbilityRate7)' value='165'></div>
                    <div class='bar_group__bar thin' label='@Html.DisplayFor(x=>x.Ability8)&nbsp;&nbsp; @Html.DisplayFor(x=>x.AbilityRate8)' value='185'></div>
                </div>
                <script src="~/AdminLTE-3.0.4/Skills_Theme/web/js/bars.js"></script>
                <div class="social-icons agileits">
                    <ul>
                        <li><a href="@Html.DisplayFor(x=>x.FacebookUrl)"></a></li>
                        <li><a href="@Html.DisplayFor(x=>x.LinkedinUrl)" class="be"></a></li>
                    </ul>
                </div>
                <div class="clear"> </div>
            </div>
        </div>
    </div>
</body>
</html>