YazarWebUygulamasi/MVCProjeKampi/MVCProjeKampi/Controllers/WriterPanelController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using BusinessLayer.ValidationRules;
using FluentValidation.Results;

namespace MVCProjeKampi.Controllers
{
    public class WriterPanelController : Controller
    {
        HeadingManager hm = new HeadingManager(new EfHeadingDal());
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        WriterManager wm = new WriterManager(new EfWriterDal());
      
        [HttpGet]
        public ActionResult WriterProfile()
        {
            string p = (string)Session["WriterMail"];
            ViewBag.d = p;
            int id = wm.GetList().Where(x => x.WriterMail == p).Select(y => y.WriterID).FirstOrDefault();
            var writerValue = wm.GetByID(id);
            return View(writerValue);
        }
        [HttpPost]
        public ActionResult WriterProfile(Writer p)
        {
            WriterValidator writerValidator = new WriterValidator();
            ValidationResult result = writerValidator.Validate(p);
            if (result.IsValid)
            {
                wm.WriterUpdate(p);
                return RedirectToAction("WriterProfile");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        public ActionResult MyHeading()
        {
            string p = (string)Session["WriterMail"];
            var writerIDInfo = wm.GetList().Where(x => x.WriterMail == p).Select(y => y.WriterID).FirstOrDefault();
            var values = hm.GetListByWriter(writerIDInfo);
            return View(values);
        }
        [HttpGet]
        public ActionResult NewHeading()
        {
            List<SelectListItem> valueCategory = (from x in cm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString()
                                                  }).ToList();
            ViewBag.vlc = valueCategory;
            return View();
        }
        [HttpPost]
        public ActionResult NewHeading(Heading p)
        {
            string writerMail = (string)Session["WriterMail"];
            var writerIDInfo = wm.GetList().Where(x => x.WriterMail == writerMail).Select(y => y.WriterID).FirstOrDefault();
            p.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            p.WriterID = writerIDInfo;
            p.HeadingStatus = true;
            hm.HeadingAdd(p);
            return RedirectToAction("MyHeading");
        }
        [HttpGet]
        public ActionResult EditHeading(int id)
        {
            List<SelectListItem> valueCategory = (from x in cm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString()
                                                  }).ToList();

            ViewBag.vlc = valueCategory;
            var headingValue = hm.GetByID(id);
            return View(headingValue);
        }
        [HttpPost]
        public ActionResult EditHeading(Heading p)
        {
            hm.HeadingUpdate(p);
            return RedirectToAction("MyHeading");
        }
        public ActionResult DeleteHeading(int id)
        {
            var headingValue = hm.GetByID(id);
            headingValue.HeadingStatus = false;
            hm.HeadingDelete(headingValue);
            return RedirectToAction("MyHeading");
        }

        public ActionResult AllHeading(int page=1)
        {
            var headings = hm.GetList().ToPagedList(page, 4);
            return View(headings);
        }
    }
}

YazarWebUygulamasi/MVCProjeKampi/MVCProjeKampi/Views/WriterPanel/AllHeading.cshtml
@using EntityLayer.Concrete
@using PagedList
@using PagedList.Mvc
@model  PagedList.IPagedList<Heading>
@{
    ViewBag.Title = "AllHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}
@{
    string color = "";
    string status = "";
    string statusColor = "";
    string deleteBtn = "";
}


<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Başlık İşlemleri</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fas fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body p-0">
            <table class="table table-striped projects">
                <thead>
                    <tr>
                        <th style="width: 1%">
                            #
                        </th>
                        <th style="width: 20%">
                            Başlık Adı
                        </th>
                        <th style="width: 15%">
                            Oluşturan Yazar
                        </th>
                        <th style="width: 8%" class="text-center">
                            Kategori
                        </th>
                        <th style="width: 20%">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        if (item.Category.CategoryName == "Film")
                        {
                            color = "badge badge-warning";
                        }
                        if (item.Category.CategoryName == "Tiyatro")
                        {
                            color = "badge badge-success";
                        }
                        if (item.Category.CategoryName == "yazılım")
                        {
                            color = "badge badge-info";
                        }
                        if (item.Category.CategoryName == "Eğitim")
                        {
                            color = "badge badge-secondary";
                        }
                        <tr>
                            <td>
                                @item.HeadingID
                            </td>
                            <td>
                                <a>
                                    @item.HeadingName
                                </a>
                                <br />
                                <small>
                                    @(((DateTime)item.HeadingDate).ToString("dd-MMM-yyyy"))
                                </small>
                            </td>
                            <td>
                                <ul class="list-inline">
                                    <li class="list-inline-item">
                                        <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                    </li>
                                </ul>
                            </td>
                            <td class="project-state">
                                <span class="@color">@item.Category.CategoryName</span>
                            </td>
                            <td class="project-actions text-right">
                                <a class="btn btn-primary btn-sm" href="/Default/Headings/@item.HeadingID">
                                    <i class="fas fa-folder">
                                    </i>
                                    Yazılar
                                </a>
                                <a class="btn btn-info btn-sm" href="/WriterPanelContent/AddContent/@item.HeadingID">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    Bu Başlığa Yaz
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</section>
@Html.PagedListPager((IPagedList)Model,page=>Url.Action("AllHeading",new {page}),new PagedListRenderOptions {

    LiElementClasses=new List<string> { "page-link"}

})

YazarWebUygulamasi/MVCProjeKampi/MVCProjeKampi/Views/WriterPanel/EditHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "EditHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h2>Başlık Güncelleme Sayfası</h2>
@using (Html.BeginForm("EditHeading", "WriterPanel", FormMethod.Post))
{
<div class="form-group">
    @Html.HiddenFor(x => x.HeadingID)
    @Html.HiddenFor(x => x.HeadingDate)
    @Html.HiddenFor(x => x.WriterID)
    @Html.Label("Başlık Adı")
    @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
    <br />
    @Html.Label("Kategori")
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Güncelle</button>
</div>
}

YazarWebUygulamasi/MVCProjeKampi/MVCProjeKampi/Views/WriterPanel/MyHeading.cshtml
@using EntityLayer.Concrete
@model List<Heading>
@{
    ViewBag.Title = "MyHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}
@{
    string color = "";
    string status = "";
    string statusColor = "";
    string deleteBtn = "";
}


<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Başlık İşlemleri</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fas fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body p-0">
            <table class="table table-striped projects">
                <thead>
                    <tr>
                        <th style="width: 1%">
                            #
                        </th>
                        <th style="width: 20%">
                            Başlık Adı
                        </th>
                        <th style="width: 15%">
                            Oluşturan Yazar
                        </th>
                        <th style="width: 8%" class="text-center">
                            Kategori
                        </th>
                        <th style="width: 20%">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        if (item.Category.CategoryName == "Film")
                        {
                            color = "badge badge-warning";
                        }
                        if (item.Category.CategoryName == "Tiyatro")
                        {
                            color = "badge badge-success";
                        }
                        if (item.Category.CategoryName == "yazılım")
                        {
                            color = "badge badge-info";
                        }
                        if (item.Category.CategoryName == "Eğitim")
                        {
                            color = "badge badge-secondary";
                        }
                        <tr>
                            <td>
                                @item.HeadingID
                            </td>
                            <td>
                                <a>
                                    @item.HeadingName
                                </a>
                                <br />
                                <small>
                                    @(((DateTime)item.HeadingDate).ToString("dd-MMM-yyyy"))
                                </small>
                            </td>
                            <td>
                                <ul class="list-inline">
                                    <li class="list-inline-item">
                                        <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                    </li>
                                </ul>
                            </td>
                            <td class="project-state">
                                <span class="@color">@item.Category.CategoryName</span>
                            </td>
                            <td class="project-actions text-right">
                                <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.HeadingID">
                                    <i class="fas fa-folder">
                                    </i>
                                    Yazılar
                                </a>
                                <a class="btn btn-info btn-sm" href="/WriterPanel/EditHeading/@item.HeadingID">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    Düzenle
                                </a>
                                <a class="btn btn-danger btn-sm" href="/WriterPanel/DeleteHeading/@item.HeadingID">
                                    <i class="fas fa-trash">
                                    </i>
                                    @deleteBtn
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</section>
<a href="/WriterPanel/NewHeading/" class="btn btn-primary">Yeni başlık girişi</a>

YazarWebUygulamasi/MVCProjeKampi/MVCProjeKampi/Views/WriterPanel/NewHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "NewHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}
<h2>Başlık Ekleme</h2>
<br />
@using (Html.BeginForm("NewHeading", "WriterPanel", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingName)
        <br />
        @Html.Label("Kategori")
        @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryID)
        <br />
        <button class="btn btn-info">Başlığı  Oluştur</button>

    </div>

}

YazarWebUygulamasi/MVCProjeKampi/MVCProjeKampi/Views/WriterPanel/WriterProfile.cshtml
@model EntityLayer.Concrete.Writer
@{
    ViewBag.Title = "WriterProfile";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}
<h2>Profilinizi Düzenleyin</h2>
<div class="form-group">
    @Html.HiddenFor(x => x.WriterID, new { @class = "form-control" })
    <br />
    @Html.Label("Kullanıcı Adı")
    @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriterName, null, new { @class = "ValidationMessageForTextColor" })
    @Html.Label("Şifre")
    @Html.TextBoxFor(x => x.WriterSurname, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriterSurname)
    @Html.Label("Email")
    @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriterMail)
    <br />
    <button class="btn btn-success">Değişiklikleri  Uygula</button>
</div>